name: test

on:
  pull_request:

jobs:
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
        config-path: .github/labeler.yml
    secrets:
         envPAT: ${{ secrets.envPAT }}
