name: test

on:
  pull_request:

jobs:
  call-workflow-passing-data:
    uses: rrr-fly-to-moon/void/.github/workflows/reusable-workflow.yml@main
    with:
        config-path: .github/labeler.yml
    secrets:
         envPAT: ${{ secrets.envPAT }}
